# Generated by Django 2.0.1 on 2020-02-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tforwardnews',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tforwardnews',
            name='mess_title',
            field=models.CharField(max_length=50),
        ),
    ]
