# Generated by Django 2.0.1 on 2020-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200220_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tserv',
            name='type',
            field=models.CharField(default='客服', max_length=30),
        ),
    ]
