# Generated by Django 2.0.1 on 2020-02-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_tserv_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tadbm',
            old_name='a_pwd',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tadbm',
            old_name='a_uname',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='tptadmin',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tptadmin',
            old_name='password',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='tserv',
            old_name='ser_pwd',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tserv',
            old_name='ser_user',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='tsup',
            old_name='sup_pwd',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tsup',
            old_name='sup_user',
            new_name='pwd',
        ),
    ]
