# Generated by Django 2.0.1 on 2020-02-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200221_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tad',
            name='is_ok',
        ),
        migrations.AlterField(
            model_name='tadbm',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
