# Generated by Django 2.0.1 on 2020-02-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Sys_Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 't_sys_role',
            },
        ),
    ]
